dataset: AmazonBooks_10104811_Chron
root: ../data
optimizer: sgd
embedding_dim: 64
num_filters: 900
alpha: 20.
lr: 0.1
weight_decay: 1.e-4
epochs: 100
hidden_dim: 512
batch_size: 8192
dropout_rate: 0.2
layers: 1
weight: 1.
upper: 0.
lower: 0.

