dataset: AmazonCDs_10104811_Chron
root: ../data
epochs: 200
batch_size: 2048
optimizer: sgd
lr: 0.1
weight_decay: 2.e-4
dropout_rate: 0.3
embedding_dim: 64
hidden_dim: 512
layers: 4
num_filters: 250
weight: .5
alpha: 10.
upper: 0.9
lower: 0.