dataset: Yelp2018_10104811_Chron
root: ../data
epochs: 200
batch_size: 2048
optimizer: sgd
lr: 0.1
weight_decay: 1.e-4 # 1.e-4 / 3.e-4
dropout_rate: 0.3
embedding_dim: 64
hidden_dim: 512
layers: 4
num_filters: 200
weight: 1.5
alpha: 5.
upper: 0.7
lower: 0.3